# Generated by Django 5.1.2 on 2024-10-25 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule_engine', '0002_remove_rule_rule_string_rule_age_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='age_condition',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rule',
            name='department_condition',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rule',
            name='experience_condition',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rule',
            name='salary_condition',
            field=models.CharField(max_length=255),
        ),
    ]
