# Generated by Django 5.1.2 on 2024-10-25 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule_engine', '0003_alter_rule_age_condition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='age_condition',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='department_condition',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='experience_condition',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='salary_condition',
        ),
        migrations.AddField(
            model_name='rule',
            name='sql_query',
            field=models.CharField(default='', max_length=255),
        ),
    ]
