# Generated by Django 5.1.2 on 2024-10-25 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule_engine', '0004_remove_rule_age_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='sql_query',
            field=models.TextField(),
        ),
    ]
