# Generated by Django 5.1.2 on 2024-10-25 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rule_engine', '0005_alter_rule_sql_query'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rule',
            old_name='sql_query',
            new_name='query',
        ),
    ]
